#!/bin/bash
# Create `fruit` that takes a fruit name and tells you its color

# validate input - expect only 1 argument
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <fruit>" >&2 # ???
	exit 1
fi

# handle the first argument
case $1 in
	banana)
		echo "yellow"
		exit 0
		;;
	apple)
		echo "red/green"
		exit 0
		;;
	strawberry)
		echo "red"
		exit 0
		;;
	*)
		echo "unknown fruit"
		exit 1
		;;
esac
