apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scratch
  name: scratch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch
  template:
    metadata:
      labels:
        app: scratch
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - mountPath: /scratch
            name: scratch-data
        ports:
          - containerPort: 9001
      volumes:
        - name: scratch-data
          persistentVolumeClaim:
            claimName: scratch-data
